version: '3.8'

services:
  postgres:
    container_name: go_gin_demo_db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: go_gin_demo
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      internal_net:
        ipv4_address: 172.28.1.1
    restart: unless-stopped

  go-gin-demo:
    container_name: go-gin-demo
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_PASSWORD: 12345678
    depends_on:
      - postgres
    networks:
      internal_net:
        ipv4_address: 172.28.1.2

networks:
  internal_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgres:
